version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: WatchTalks/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - dbdata:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  dbdata: